/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Version: 2.1.0
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[Object.keys(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// node_modules/ip/lib/ip.js
var require_ip = __commonJS({
  "node_modules/ip/lib/ip.js"(exports) {
    var ip2 = exports;
    var { Buffer: Buffer2 } = require("buffer");
    var os = require("os");
    ip2.toBuffer = function(ip3, buff, offset) {
      offset = ~~offset;
      var result;
      if (this.isV4Format(ip3)) {
        result = buff || new Buffer2(offset + 4);
        ip3.split(/\./g).map((byte) => {
          result[offset++] = parseInt(byte, 10) & 255;
        });
      } else if (this.isV6Format(ip3)) {
        var sections = ip3.split(":", 8);
        var i;
        for (i = 0; i < sections.length; i++) {
          var isv4 = this.isV4Format(sections[i]);
          var v4Buffer;
          if (isv4) {
            v4Buffer = this.toBuffer(sections[i]);
            sections[i] = v4Buffer.slice(0, 2).toString("hex");
          }
          if (v4Buffer && ++i < 8) {
            sections.splice(i, 0, v4Buffer.slice(2, 4).toString("hex"));
          }
        }
        if (sections[0] === "") {
          while (sections.length < 8)
            sections.unshift("0");
        } else if (sections[sections.length - 1] === "") {
          while (sections.length < 8)
            sections.push("0");
        } else if (sections.length < 8) {
          for (i = 0; i < sections.length && sections[i] !== ""; i++)
            ;
          var argv = [i, 1];
          for (i = 9 - sections.length; i > 0; i--) {
            argv.push("0");
          }
          sections.splice.apply(sections, argv);
        }
        result = buff || new Buffer2(offset + 16);
        for (i = 0; i < sections.length; i++) {
          var word = parseInt(sections[i], 16);
          result[offset++] = word >> 8 & 255;
          result[offset++] = word & 255;
        }
      }
      if (!result) {
        throw Error(`Invalid ip address: ${ip3}`);
      }
      return result;
    };
    ip2.toString = function(buff, offset, length) {
      offset = ~~offset;
      length = length || buff.length - offset;
      var result = [];
      var i;
      if (length === 4) {
        for (i = 0; i < length; i++) {
          result.push(buff[offset + i]);
        }
        result = result.join(".");
      } else if (length === 16) {
        for (i = 0; i < length; i += 2) {
          result.push(buff.readUInt16BE(offset + i).toString(16));
        }
        result = result.join(":");
        result = result.replace(/(^|:)0(:0)*:0(:|$)/, "$1::$3");
        result = result.replace(/:{3,4}/, "::");
      }
      return result;
    };
    var ipv4Regex = /^(\d{1,3}\.){3,3}\d{1,3}$/;
    var ipv6Regex = /^(::)?(((\d{1,3}\.){3}(\d{1,3}){1})?([0-9a-f]){0,4}:{0,2}){1,8}(::)?$/i;
    ip2.isV4Format = function(ip3) {
      return ipv4Regex.test(ip3);
    };
    ip2.isV6Format = function(ip3) {
      return ipv6Regex.test(ip3);
    };
    function _normalizeFamily(family) {
      if (family === 4) {
        return "ipv4";
      }
      if (family === 6) {
        return "ipv6";
      }
      return family ? family.toLowerCase() : "ipv4";
    }
    ip2.fromPrefixLen = function(prefixlen, family) {
      if (prefixlen > 32) {
        family = "ipv6";
      } else {
        family = _normalizeFamily(family);
      }
      var len = 4;
      if (family === "ipv6") {
        len = 16;
      }
      var buff = new Buffer2(len);
      for (var i = 0, n = buff.length; i < n; ++i) {
        var bits = 8;
        if (prefixlen < 8) {
          bits = prefixlen;
        }
        prefixlen -= bits;
        buff[i] = ~(255 >> bits) & 255;
      }
      return ip2.toString(buff);
    };
    ip2.mask = function(addr, mask) {
      addr = ip2.toBuffer(addr);
      mask = ip2.toBuffer(mask);
      var result = new Buffer2(Math.max(addr.length, mask.length));
      var i;
      if (addr.length === mask.length) {
        for (i = 0; i < addr.length; i++) {
          result[i] = addr[i] & mask[i];
        }
      } else if (mask.length === 4) {
        for (i = 0; i < mask.length; i++) {
          result[i] = addr[addr.length - 4 + i] & mask[i];
        }
      } else {
        for (i = 0; i < result.length - 6; i++) {
          result[i] = 0;
        }
        result[10] = 255;
        result[11] = 255;
        for (i = 0; i < addr.length; i++) {
          result[i + 12] = addr[i] & mask[i + 12];
        }
        i += 12;
      }
      for (; i < result.length; i++) {
        result[i] = 0;
      }
      return ip2.toString(result);
    };
    ip2.cidr = function(cidrString) {
      var cidrParts = cidrString.split("/");
      var addr = cidrParts[0];
      if (cidrParts.length !== 2) {
        throw new Error(`invalid CIDR subnet: ${addr}`);
      }
      var mask = ip2.fromPrefixLen(parseInt(cidrParts[1], 10));
      return ip2.mask(addr, mask);
    };
    ip2.subnet = function(addr, mask) {
      var networkAddress = ip2.toLong(ip2.mask(addr, mask));
      var maskBuffer = ip2.toBuffer(mask);
      var maskLength = 0;
      for (var i = 0; i < maskBuffer.length; i++) {
        if (maskBuffer[i] === 255) {
          maskLength += 8;
        } else {
          var octet = maskBuffer[i] & 255;
          while (octet) {
            octet = octet << 1 & 255;
            maskLength++;
          }
        }
      }
      var numberOfAddresses = Math.pow(2, 32 - maskLength);
      return {
        networkAddress: ip2.fromLong(networkAddress),
        firstAddress: numberOfAddresses <= 2 ? ip2.fromLong(networkAddress) : ip2.fromLong(networkAddress + 1),
        lastAddress: numberOfAddresses <= 2 ? ip2.fromLong(networkAddress + numberOfAddresses - 1) : ip2.fromLong(networkAddress + numberOfAddresses - 2),
        broadcastAddress: ip2.fromLong(networkAddress + numberOfAddresses - 1),
        subnetMask: mask,
        subnetMaskLength: maskLength,
        numHosts: numberOfAddresses <= 2 ? numberOfAddresses : numberOfAddresses - 2,
        length: numberOfAddresses,
        contains(other) {
          return networkAddress === ip2.toLong(ip2.mask(other, mask));
        }
      };
    };
    ip2.cidrSubnet = function(cidrString) {
      var cidrParts = cidrString.split("/");
      var addr = cidrParts[0];
      if (cidrParts.length !== 2) {
        throw new Error(`invalid CIDR subnet: ${addr}`);
      }
      var mask = ip2.fromPrefixLen(parseInt(cidrParts[1], 10));
      return ip2.subnet(addr, mask);
    };
    ip2.not = function(addr) {
      var buff = ip2.toBuffer(addr);
      for (var i = 0; i < buff.length; i++) {
        buff[i] = 255 ^ buff[i];
      }
      return ip2.toString(buff);
    };
    ip2.or = function(a, b) {
      var i;
      a = ip2.toBuffer(a);
      b = ip2.toBuffer(b);
      if (a.length === b.length) {
        for (i = 0; i < a.length; ++i) {
          a[i] |= b[i];
        }
        return ip2.toString(a);
      }
      var buff = a;
      var other = b;
      if (b.length > a.length) {
        buff = b;
        other = a;
      }
      var offset = buff.length - other.length;
      for (i = offset; i < buff.length; ++i) {
        buff[i] |= other[i - offset];
      }
      return ip2.toString(buff);
    };
    ip2.isEqual = function(a, b) {
      var i;
      a = ip2.toBuffer(a);
      b = ip2.toBuffer(b);
      if (a.length === b.length) {
        for (i = 0; i < a.length; i++) {
          if (a[i] !== b[i])
            return false;
        }
        return true;
      }
      if (b.length === 4) {
        var t = b;
        b = a;
        a = t;
      }
      for (i = 0; i < 10; i++) {
        if (b[i] !== 0)
          return false;
      }
      var word = b.readUInt16BE(10);
      if (word !== 0 && word !== 65535)
        return false;
      for (i = 0; i < 4; i++) {
        if (a[i] !== b[i + 12])
          return false;
      }
      return true;
    };
    ip2.isPrivate = function(addr) {
      if (ip2.isLoopback(addr)) {
        return true;
      }
      if (!ip2.isV6Format(addr)) {
        const ipl = ip2.normalizeToLong(addr);
        if (ipl < 0) {
          throw new Error("invalid ipv4 address");
        }
        addr = ip2.fromLong(ipl);
      }
      return /^(::f{4}:)?10\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/i.test(addr) || /^(::f{4}:)?192\.168\.([0-9]{1,3})\.([0-9]{1,3})$/i.test(addr) || /^(::f{4}:)?172\.(1[6-9]|2\d|30|31)\.([0-9]{1,3})\.([0-9]{1,3})$/i.test(addr) || /^(::f{4}:)?169\.254\.([0-9]{1,3})\.([0-9]{1,3})$/i.test(addr) || /^f[cd][0-9a-f]{2}:/i.test(addr) || /^fe80:/i.test(addr) || /^::1$/.test(addr) || /^::$/.test(addr);
    };
    ip2.isPublic = function(addr) {
      return !ip2.isPrivate(addr);
    };
    ip2.isLoopback = function(addr) {
      if (!/\./.test(addr) && !/:/.test(addr)) {
        addr = ip2.fromLong(Number(addr));
      }
      return /^(::f{4}:)?127\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})/.test(addr) || /^0177\./.test(addr) || /^0x7f\./i.test(addr) || /^fe80::1$/i.test(addr) || /^::1$/.test(addr) || /^::$/.test(addr);
    };
    ip2.loopback = function(family) {
      family = _normalizeFamily(family);
      if (family !== "ipv4" && family !== "ipv6") {
        throw new Error("family must be ipv4 or ipv6");
      }
      return family === "ipv4" ? "127.0.0.1" : "fe80::1";
    };
    ip2.address = function(name, family) {
      var interfaces = os.networkInterfaces();
      family = _normalizeFamily(family);
      if (name && name !== "private" && name !== "public") {
        var res = interfaces[name].filter((details) => {
          var itemFamily = _normalizeFamily(details.family);
          return itemFamily === family;
        });
        if (res.length === 0) {
          return void 0;
        }
        return res[0].address;
      }
      var all = Object.keys(interfaces).map((nic) => {
        var addresses = interfaces[nic].filter((details) => {
          details.family = _normalizeFamily(details.family);
          if (details.family !== family || ip2.isLoopback(details.address)) {
            return false;
          }
          if (!name) {
            return true;
          }
          return name === "public" ? ip2.isPrivate(details.address) : ip2.isPublic(details.address);
        });
        return addresses.length ? addresses[0].address : void 0;
      }).filter(Boolean);
      return !all.length ? ip2.loopback(family) : all[0];
    };
    ip2.toLong = function(ip3) {
      var ipl = 0;
      ip3.split(".").forEach((octet) => {
        ipl <<= 8;
        ipl += parseInt(octet);
      });
      return ipl >>> 0;
    };
    ip2.fromLong = function(ipl) {
      return `${ipl >>> 24}.${ipl >> 16 & 255}.${ipl >> 8 & 255}.${ipl & 255}`;
    };
    ip2.normalizeToLong = function(addr) {
      const parts = addr.split(".").map((part) => {
        if (part.startsWith("0x") || part.startsWith("0X")) {
          return parseInt(part, 16);
        } else if (part.startsWith("0") && part !== "0" && /^[0-7]+$/.test(part)) {
          return parseInt(part, 8);
        } else if (/^[1-9]\d*$/.test(part) || part === "0") {
          return parseInt(part, 10);
        } else {
          return NaN;
        }
      });
      if (parts.some(isNaN))
        return -1;
      let val = 0;
      const n = parts.length;
      switch (n) {
        case 1:
          val = parts[0];
          break;
        case 2:
          if (parts[0] > 255 || parts[1] > 16777215)
            return -1;
          val = parts[0] << 24 | parts[1] & 16777215;
          break;
        case 3:
          if (parts[0] > 255 || parts[1] > 255 || parts[2] > 65535)
            return -1;
          val = parts[0] << 24 | parts[1] << 16 | parts[2] & 65535;
          break;
        case 4:
          if (parts.some((part) => part > 255))
            return -1;
          val = parts[0] << 24 | parts[1] << 16 | parts[2] << 8 | parts[3];
          break;
        default:
          return -1;
      }
      return val >>> 0;
    };
  }
});

// src/main.tsx
__export(exports, {
  default: () => AdvancedCalibrePlugin
});
var import_obsidian7 = __toModule(require("obsidian"));

// src/BookSuggestModal.ts
var import_obsidian = __toModule(require("obsidian"));
var BookSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, books, onChoose) {
    super(app);
    this.books = books;
    this.onChoose = onChoose;
    this.setPlaceholder("Search your calibre library...");
  }
  getItems() {
    return this.books;
  }
  getItemText(book) {
    var _a, _b, _c, _d, _e;
    const authors = (_c = (_b = (_a = book.authors) == null ? void 0 : _a.join(", ")) != null ? _b : book.author_sort) != null ? _c : "";
    return authors ? `${(_d = book.title) != null ? _d : "Untitled"} \u2014 ${authors}` : (_e = book.title) != null ? _e : "Untitled";
  }
  onChooseItem(book) {
    this.onChoose(book);
  }
};

// src/AdvancedCalibreImporter.ts
var import_obsidian5 = __toModule(require("obsidian"));

// src/settings.tsx
var import_obsidian4 = __toModule(require("obsidian"));

// src/FolderSuggest.ts
var import_obsidian2 = __toModule(require("obsidian"));
var FolderSuggest = class extends import_obsidian2.AbstractInputSuggest {
  constructor(app, textInputEl) {
    super(app, textInputEl);
    this.textInputEl = textInputEl;
  }
  getSuggestions(query) {
    const search = query.toLowerCase();
    return this.app.vault.getAllLoadedFiles().filter((file) => file instanceof import_obsidian2.TFolder).filter((folder) => folder.path.toLowerCase().contains(search));
  }
  renderSuggestion(folder, el) {
    el.setText(folder.path || "/");
  }
  selectSuggestion(folder) {
    this.textInputEl.value = folder.path;
    this.textInputEl.trigger("input");
    this.close();
  }
};

// src/TemplateFileSuggest.ts
var import_obsidian3 = __toModule(require("obsidian"));
var TemplateFileSuggest = class extends import_obsidian3.AbstractInputSuggest {
  constructor(app, textInputEl) {
    super(app, textInputEl);
    this.textInputEl = textInputEl;
  }
  getSuggestions(query) {
    const search = query.toLowerCase();
    return this.app.vault.getMarkdownFiles().filter((file) => file.path.toLowerCase().contains(search));
  }
  renderSuggestion(file, el) {
    el.setText(file.path);
  }
  selectSuggestion(file) {
    this.textInputEl.value = file.path;
    this.textInputEl.trigger("input");
    this.close();
  }
};

// src/tools.ts
var ADVANCED_CALIBRE_ICON_ID = "advanced-calibre";
var ADVANCED_CALIBRE_ICON_SVG = `
<g transform="translate(-24.920761,-148.42979)">
	<image width="100" height="100" preserveAspectRatio="none" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADkAAAA5CAYAAACMGIOFAAAACXBIWXMAABYlAAAWJQFJUiTwAAAU
	BklEQVRoge2aaWxk2XXff+fe92onWWSRLC7NbrK7p6d7emZ6RiNZYy2j2AqCSeLYQGAktqMEgQ0k
	gT/4SwI4XwwjQZDYCZDAcIwYhr/YsaMPQgLYGW2WMtJI1hKNPKPp2Vq9kt3ct2JtrOW9e08+vKpu
	LsVWj90B8iEHKBBVfPfd+7/nnP8595wrHBYRMDyiKPjkz48WETEoFlR74/yjzvNXFXt0LTxY+KN8
	5APMpb13exHUGDGZIBgpZtLnjRHpOt/8gO97ZAkOfTFkhgIu6o+eTADXiHk/9nR+xINGwY9lM5dm
	c/mfy9ngVNbYMxmxpzLWjOdNUKpo95UvLN/7OyjCI1rGB5GgtxCr4J4d5TcWhvmVyOPkuJbvi4IL
	DfZWjX//gx1+tT/+BJgG1D9ZGP7Fy/niv+g6Fxsl8F6JIu+7cYTgz4XGSOS8T5bzeIEGHHhjPuSs
	8+AUlYdMpOCNxw6FnD84/sSngXqne3c3atHyLhYjEqStZPIhw8UccxOZyW9/a2e00mjvioA+Zl32
	NdlfqLMGvEfkISarINYkGkUMRghOMnEjYp1zcVhKL3/8U+fIjoTheDlnx8azDBfTmh9Kkc+Ho1/+
	pbsTlRvtXRER1ccLs69JBbi2x9DdBvgfPYUYgWZMDvV4JeYkczXiAbKj9vZnfvlZmu3IouC94mIv
	UeQ9HjNZys+8e2P7hw/b3L+sHCKeoZB4OAXuBLUcpFMjYI24iSs//rOFoaEr3rkWIseGiUDkIJ2J
	Gqtrtb10Kix6VRVBQFBVH4bGLMyNnPnadyF5x+O11z5IAZgr0J7MQuTB9NZ70HKsMXivKIh4pZMf
	HSt9+uXfCgM70zOxgXujiAQSbUastnNWUS/HHpyeKCw8VmQH5JAmY49EDmIg7ijqIJUVjIBzSrXm
	yWTBBAIOHNhOu+VdsvfxSSBFJGx2u7Vqo9sYy6emYqdKH6cI3itTE4X55OnHHkGOZzcigotgYrrI
	9IUZuh2lXlPCVMiLLz9PujiEOsUIiKIiYsUaEBMgMvBjAku766LNnebdwBoOEouAOKeUS7k5AK/6
	2DOhYyCNEbpteOqFC5w5O8Xs6RJ/8zN/jdh5xosZzl48Q6eV+JqIiBiDiMFaQ2AtQRAQ9j5BEGCt
	JbCWOFa/tFJbtFYOeZwIEsWOmcnCqXwutKp4OW7NfyUJjv6gqgQB7O7U+N53VigEHc5FXe4uOV7/
	1j0mZjMYC95DvlAw0xMTJmWFbCZDNp0mnU4RGEPsHO1ul1a7Q+xj4o6aje39u8eXIBI7ZbiQniwO
	Zcaa+9HW484HjoEUEaJIKZXy/Mbv/iNqOzUmp0Z59so8s2cm+aPf+xLeg7HQaNT96uaGD405viTV
	+78FgWV7ryqtjdodr8rBMCGCeO/JZcOR8bHs5MpGfUsEOTD88YNUVYIUbC5v89r/+AaN6j6xV6wR
	CsM5quu7BCGH0nRFH8oXqmCtCde2msvdyHsROeQmXvGplDXlUv4U8O7/dXP1Xkln4N03lvhmJYmZ
	o8PQbMDoRJ7p+dwHnkRRwsCEqxv19VqjU8nnMiXnvPbBqKoPjJizp4vzAMKjxcpHzY6OE48IcQSl
	iRy//Qef4Td//xewQ1me/cgk//H3/yFjxTxx/IFRElgT7NU6lWqtsxVY4WCs6HvgzGQSRgasWkCM
	iLHGBoEYGwCiqioDEpCjctwnjdBuKx/+2BO8/ufvc+/WOv/8X77M1GSBP/ovf8ab31mkMGzw3Udn
	egWMEdNsdRuVWntl4bS5qIreX54Izinl8fyZ5Ksxxpok5fReVb0DVVVFne+t05BK59PddqP7gUH2
	2bVaa3F7aZed9T0ubVb57B9+k047YvrsKDsrFcJHrh8kKI0R0+3Eur7VWAqsuZ8vQz9WeibH8qcB
	4jiOOPh/YwJrSzNDpfnzT338bzxVXvjQs6NT554anXriwp/81s//7I3X//QbYqxV7wbmzwPZ1cVK
	NmP5tV//KSo7DVDl0j97ifGZUX7nt19l/U6F9AdyTUUEwXsWl6uL1vbPU/2kRyRynqnx7HR5amrE
	Dp8/MzX/zOXp8y88kx2eeebV/7p8sd2cncsVbfqlv/9RssNFOvtRnBsKg3PP//WfuPH6n35DROQk
	5xxAPEnq9u6bd3n1i9fBOUwAuxUYL4WMlQJSmSROfkBRgNWtxtLRfyRhBLJp8r/4r/7nK2bmw59I
	Wa+IEe8cr3/hOzSrEdWtbb96c8mfulQkanvfCWFs6tJzkJj1SRMfNzoFG8DGWpNnPzzN2PwoE9PD
	/Nq/+0kWrsywvNoiFZq/ZIopbG7vLzmvcDiMiPeQCckXh6XUaUGrFsfNShyrN644abxqV12UNrWd
	/SAICMQEgYtgcv7K5Uy+GKh6dxIJHdOkMcJ+XXnxY7P841/6KLcXK4TpgMrqHj/98jm2VndobDUI
	jm6PKl4VYwY7qyqKNWZtq7Hc6cRqEpD3bVYRrLh00PjhMsUXLhlrAxUjNhDGpgugVbwPqaw3kl0R
	I95BbmTizMjE6dPt5t5tRIQBIeU48ZDkpUOjWf7JP/0CuRCuvDjLH3zuJh97apTJ6Rx76w3CfgVI
	erE1DEmnU9Sb+yeAVA0CE6xuNraq9U6lkAvHYqf0915V1QZBmOnebsQxrXRosr3NoTRTQIwHSVFZ
	b+HiCCQU72KXywepyfnnntpYvHpbMKIDKp0DiCfxN6Oef/NvP0Gj3mF4OM3HX5yiNJ7js599+7Cp
	KhgrdOOY4UKB4XKBdCrFdmWPSq2GfaBZtdYEtXqrtlfvbIwMpcdiFyv3YXpvbMoGnaVO1NrfknTu
	tDivPhYZLQ8RpAQXW6pbEd12kyAs4ryqCEyf+9Bzb3/9D1/hhExpQAiBIICN1RrfffUGtVobRFCF
	YjFDt97CnFDH29jZYWFulnwmw541h86GmoQR2/FQqbaXz86NXDoUKxUwITm2w05j464pLZwmQp1D
	hko5sgVLYw8ae8p+rUZxsoiLRZyD8VOXn4eTyec4SK+k0/DetR2++vXtpC7Z024QCOUypFKCxsff
	Z6yl1e5QLBQwxuBVCQ7srekRw+pmfemjdppDSbioKJZCqjlSX33nlpxd+AQkaUB2KMNQKUW94mg3
	DfWdKmNTgIi4CMbnnr6czg7bTqvmBvnlYOJpKJ/61BSXr0xR3WsRBJY49kxO5vjyV5a4dnWbXPr4
	jqn3GBGstWQzaQJr8V4xNjHZvtbuLFcXjRH0QNVIEGKnjI+Ek+7ardcSnSjqlTBrGS3nWLleJY5C
	Khs15p9J3uhiGBqdmi+W5+c2Fq8uDspnB1KhCMRdR1RvETU6dOst2rUWu2s1JI6RAaP6+WcQBATW
	UsjlmJmcQJOj1SHZ2Gou9sYcOnI55xnKZ6a6O+8vRxGIGKualKfHpvOgDj3IsBjx3vkwQ3p87vKl
	/m9H1zbwFJLJwBtvbvH1b2wmGlJIp4TpM1mqlQ6p8IRSjCrFoSE63YgbS/fIZzIY8yCm9s1zbaux
	FMeeI3FNnPfkC/kJX79Za9bbmyNDmUkfeVUvUpoZQqxHSFNZb+KiDkgavHpjMDPnP/L8u9/87BcH
	kc+JGaiIMlEyTJQMk+OGQgF+4sVJzp0r0u48ML1k9dwPJTt7ezjvmSqNsbm723tODz7J1u7+Wjdy
	kTyIlb0N9i6TyUjBVEx1e/m6TVSgzkGxnCeVFhBDbTui02rSI+6EfOaePpF8BpsrSXBe3/ZsbHu2
	djz3VpUvfXULFzuO5hVJNcGxMDdLu9NhpJBPOj3mcGbU95X17ebWXr2zG1g5Go40CFOUh7vFjcWr
	V4NUsurE7/JkhwIEaNagWa1hbJL3ughKsxefDtN5o+rd0frvQOJpNZRPfnyUJy8VqVa7BIEQx8qp
	mRxffW1zsKlKQjzOexZX1zhVniSKYla3tgmD4IEagb1ap1apttfGRjLlyMUqB7ZNESZGw7lvLb/9
	pjF/FwDvIFNIMzKeprLepVk11HdrjJ9KttjFMDw+Nz86dXZuc+ntpaPkM9hcBXzskG6EdGOkG2Pj
	mNZei24r4mjmpiSF57WtbeamyszPTrPfbie7aO0DRu/5ZBw7tnb3l23SUHlwpOqRT3l86PzO3bfe
	jeOkeauqhGlDYbTA1MIKpZmI9duVXrwW8d75VIZMafbiQPI5kXj+4mqV175dRQScg1od8gXD6TlL
	EHDUDLHWour5wbXrzJYn2avVaXU6BNYesp6kXItu7uwv2cRcD8RKJIpjpiZHzzc237/bariWsTbr
	4iSjHz8VMXthgrNXfpxbP3iDuJu4ivbIZ/bCi8+//+3Pfeko+ZxMPArZTKKl4qjhZ/7WML/zmwuc
	O5+n3eaQNoXkiDY/O8v503O0Ox1SYXAwpTsmi8t7i0kr4hBGiSLHVLk4F8bbtb3tlZs2ADFotwVP
	f/IJnnjhY4xMjvHsp14ijpKmjYiIdzBx+pmB5HNMk/2GurHCqZkUL/3YMB+9UmB9K+LVr22zudIi
	lYJDdW4R1HvuLK/wwuVLXDq3wObOLv/76jukU6mBIFc2G3d61nAwVuKcpzicL+dsM7V25+oPZuZP
	PxN11HuPyQ6XAIg6ikjq4ECJ75NPTqLO/qHMZ0CbADpduLCQ5j/86imcKr/739b5z3+8xedeqbKy
	1iUVysD2Xiad5u3rN1nd2KLd7fYaVMcrsgDrW417sfPIsXOl+nQmNMWCKa/c/IvvmeBB00ldkgEd
	PTaKmPvkUyyfnevhvv/QMZDqIZ2G92+2+ZVfX+TW7SYvPJPhyqWQkZIQphOAg46nzjlOT5cZyufo
	dLtJCBmEkCRWtjtx2xyxWVXVwBpOTQ2f3Vh85/Xe2e9AXjjwoCGakE+2NPNkj3weAvLB7sDmtuP1
	N1t86atVtOP45X9Q5MKFNO22Huav3mG52WpRb7bY2auysb17v/03SNa3mtuVans7aQBxOFriOb9Q
	vrB+58332k1iY44caQaIqnpjYOaJjzzXA/AQkP19FQizQpiCnarnK3/e4r+/UmN7MyIMj3Sj5QHD
	drpd0qkUc1Plh63J1Oqd1s5eay0IDne5QPDOMzsz9mS0d7feqKwu2gCOJt3Hli2CdzA5/9yHEtD+
	5DhpBPbb8OKVFD/zkxmiGEILuSzkcyC9Zs8hHWmvyuccYRgQBJa7a+uDKhHJHEaMAjuV1j1rj/oX
	EjvPTHnkHERsL19724Zw4sseDDRxDKWZJ58Owoyof5D5HPdJILAQq/KVb3WS+mqPP1ThiXlLN+bw
	SaQHcKRQQL2yvr3DmdlpSsUi3vsBRJH8sLHTXLLmsLmKIHHsmRgrnAJYvvH69x9Rk+IiGJmYXxid
	PpfkQpwAEhJNua7HpmCnClEEWxWYnxEKKT+4HCmC10TFURyTDlN49QMV0Md8++7enSMJPCASx57x
	sezkWB6zevutw+TzEJjeO5/Kki3NXLzYBz4QpCqEIdxc8vzcp4VPviiUy8Iv/G3D3/u08P23HNmM
	cKwfrIqIYXJsjPmZae6urVGp1nqZ0BGgPc2tbNQXvfZLZw82wHklnwlGpyYLcys33rja3Sd6FPLh
	BPI5scaztad88TXPz78sjI1ApwP/6Y9jlreUXCZpuR+o4GCNoRtF7NXrLK6ukstkSIUhURwfU0K/
	RbC5u78SRx4RDsfK3o2QqfLo2ffu3P5ao7K6VCjNnI+jhzd4+uRTPkI+hy4rWUEDA+pgKANLa8q/
	/j0lm4ZWJ9HwcBach9CACnhVvFe8gsaOlY1NvPfU6k2M6SUdveSj73p9H9za2V9rdeKGMVLoLUFU
	wXvvBTUz5ZEFuPe1vc1b742UZ87H3QFlhsMoTRzD6PSFp22YwkVdh4gcuqx0vUphZf9BeBBJ2Na3
	e0TTAV/vlUciKFkjL5VGJZPJkEmlyGbSpMMQay3OOdrdiHanTSeKqdVqGDH9fiQAGzvNne3d/a3y
	eL4QxV6tFbGBIQiFfCHF5Yvls/zJO6zeeP3Ns89/8qdVVR+O8QD5TJ2f3b733or0QfYlbfEZO+BG
	1oFCcv9v6MGK1716Q01zHyOCGMH0TFN7RSjvPSpCt906yJAKSHM/6jY70VpxNLNQrXW023HU9tpU
	dlpcq2+zdrO+ALCx9NYbyciH9iJVFfWuG2fyqfzY9IUnt++9tyIY6ZurKHBmiP1y77LSQzubAuKg
	k0Hb3QhrhX7s1QeP3BdjLFHsDp+qBKOK+7PP315+77UN7i5VtVbp0NjraHs/Vu16msbPAKzffuvd
	TouusTZFv4Gv6lX7N6fEiDEmCEUkbfzQGJTnLz59/Xu8inDfXAFwHunGECnxQ/vZgicm5XvWLAnA
	+IStVtSHAv4QafS86+tfvr14xuRQwacDQ2iNZILABimhYHQuqGB212/daeyuLBZGZy94F3sTBDYM
	xdrAJBV/B92Odms7m/cqqz+8Xtm8/f61777yeQD13h8iHlUamQCsx8qgY9gD8RJA1emuTadns6kQ
	rxowyABUvbEB+/WaujhpkipJ215VcSG3J0dyNGJnHOrb6mtN113rRH5nz3W/osZq3G5odevmOzNP
	zF5oVIx29lvbG3du3NrbvP3e9r13r67d/P67lY1b16tbi6vdVj06Mr0/4GXoUMjpqSwv82j3w2W1
	xefHn3jmmeFi8Zx3rjPoAiGqaoIgVd3avH73+rX/dWBPBdB8KhyfyuZ+quXilbZ3y53YbbTjeM/5
	JBKLGFH1OnP+xy5Nn/vICxt3r17d27i12NhdrQ1clIgRY4167/oh5LFeJXnM0rvZduKNaDHG2MRB
	9L4MSrGOghR5yLXso6LgxBgjj7BZmljOoAX351Tue81xPhBjjIgxqPr7gB7/dfX/L/9Py/8Bsk9P
	/55ysxEAAAAASUVORK5CYII=" x="24.920761" y="148.42979"/>
</g>`;

// src/settings.tsx
var DEBOUNCE_TIMEOUT = 1e3;
var DEFAULT_SETTINGS = {
  address: "http://localhost:8080",
  displayText: "Advanced Calibre",
  splitDirection: "tab",
  ribbonIcon: ADVANCED_CALIBRE_ICON_ID,
  hideRibbonIcon: false,
  replaceLocalIp: true,
  localIpOverride: "",
  importFolder: "Sources",
  filenameTemplate: "{{author}} - {{title}}",
  importCover: true,
  coverFolder: "",
  coverWidth: 350,
  importLibrary: "Calibre_Library",
  autoOpenAfterImport: true,
  noteGeneration: "built-in",
  customTemplateFile: "",
  headingTemplate: "# {{title}}",
  bylineTemplate: "{{byline}}",
  coverTemplate: "![[{{cover}}|{{coverWidth}}]]",
  descriptionTemplate: "## Description\n\n{{description}}",
  tagSpaceHandling: "hyphenate",
  maxTags: 10
};
var AdvancedCalibreSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Advanced Calibre Settings" });
    new import_obsidian4.Setting(containerEl).setName("Server Address").setDesc("The address of calibre Content server.").addText((text) => {
      text.inputEl.size = 25;
      text.setPlaceholder(DEFAULT_SETTINGS.address).setValue(this.plugin.settings.address).onChange((0, import_obsidian4.debounce)((value) => __async(this, null, function* () {
        this.plugin.settings.address = value;
        this.plugin.saveData(this.plugin.settings);
      }), DEBOUNCE_TIMEOUT));
    });
    new import_obsidian4.Setting(containerEl).setName("Use the local IP address instead of 'localhost'").addToggle((toggle) => toggle.setValue(this.plugin.settings.replaceLocalIp).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.replaceLocalIp = value;
      this.plugin.saveData(this.plugin.settings);
    })));
    new import_obsidian4.Setting(containerEl).setName("Local IP override").setDesc("Only used if the setting above is on. Leave blank to auto-detect. If auto-detect picks the wrong network adapter (common with VPNs, Docker, or virtual machines installed), enter your computer's real local IP address here instead, e.g. 192.168.1.100.").addText((text) => {
      text.inputEl.size = 25;
      text.setPlaceholder("Auto-detect (e.g. 192.168.1.100)").setValue(this.plugin.settings.localIpOverride).onChange((0, import_obsidian4.debounce)((value) => __async(this, null, function* () {
        this.plugin.settings.localIpOverride = value;
        this.plugin.saveData(this.plugin.settings);
      }), DEBOUNCE_TIMEOUT));
    });
    new import_obsidian4.Setting(containerEl).setName("View Display Text").setDesc("The title of calibre view.").addText((text) => {
      text.inputEl.size = 25;
      text.setPlaceholder(DEFAULT_SETTINGS.displayText).setValue(this.plugin.settings.displayText).onChange((0, import_obsidian4.debounce)((value) => __async(this, null, function* () {
        this.plugin.settings.displayText = value;
        this.plugin.saveData(this.plugin.settings);
      }), DEBOUNCE_TIMEOUT));
    });
    new import_obsidian4.Setting(containerEl).setName("Open In").setDesc("Full tab opens calibre as its own tab. The split options open it alongside the current pane.").addDropdown((dropdown) => dropdown.addOption("tab", "Full tab").addOption("horizontal", "Horizontal split").addOption("vertical", "Vertical split").setValue(this.plugin.settings.splitDirection).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.splitDirection = value;
      this.plugin.saveData(this.plugin.settings);
    })));
    containerEl.createEl("h3", { text: "Metadata Import" });
    new import_obsidian4.Setting(containerEl).setName("Library").setDesc("The calibre library to import from, as it appears in the library chooser.").addText((text) => {
      text.inputEl.size = 25;
      text.setPlaceholder("Calibre_Library").setValue(this.plugin.settings.importLibrary).onChange((0, import_obsidian4.debounce)((value) => __async(this, null, function* () {
        this.plugin.settings.importLibrary = value;
        this.plugin.saveData(this.plugin.settings);
      }), DEBOUNCE_TIMEOUT));
    });
    new import_obsidian4.Setting(containerEl).setName("Import Folder").setDesc("Where imported book notes are created. Created if it does not exist.").addText((text) => {
      text.inputEl.size = 25;
      new FolderSuggest(this.app, text.inputEl);
      text.setPlaceholder("Sources").setValue(this.plugin.settings.importFolder).onChange((0, import_obsidian4.debounce)((value) => __async(this, null, function* () {
        this.plugin.settings.importFolder = value;
        this.plugin.saveData(this.plugin.settings);
      }), DEBOUNCE_TIMEOUT));
    });
    new import_obsidian4.Setting(containerEl).setName("Filename Template").setDesc("Available: {{title}}, {{author}} (sort order), {{authors}}, {{year}}, {{publisher}}, {{series}}, {{id}}. Characters illegal in filenames are removed automatically.").addText((text) => {
      text.inputEl.size = 25;
      text.setPlaceholder("{{author}} - {{title}}").setValue(this.plugin.settings.filenameTemplate).onChange((0, import_obsidian4.debounce)((value) => __async(this, null, function* () {
        this.plugin.settings.filenameTemplate = value;
        this.plugin.saveData(this.plugin.settings);
      }), DEBOUNCE_TIMEOUT));
    });
    new import_obsidian4.Setting(containerEl).setName("Open Note After Import").setDesc("Opens the newly imported note automatically. Turn off to stay on the current pane.").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoOpenAfterImport).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.autoOpenAfterImport = value;
      this.plugin.saveData(this.plugin.settings);
    })));
    containerEl.createEl("h3", { text: "Tags" });
    new import_obsidian4.Setting(containerEl).setName("Tag Space Handling").setDesc("calibre tags are free text and often contain spaces, which Obsidian tags can't \u2014 they'd otherwise render struck through as invalid.").addDropdown((dropdown) => dropdown.addOption("hyphenate", "Hyphenate (old testament \u2192 old-testament)").addOption("camelCase", "CamelCase (old testament \u2192 OldTestament)").addOption("none", "Leave as-is (may not render as a tag)").setValue(this.plugin.settings.tagSpaceHandling).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.tagSpaceHandling = value;
      this.plugin.saveData(this.plugin.settings);
    })));
    new import_obsidian4.Setting(containerEl).setName("Max Tags").setDesc("Caps how many tags are imported per book, keeping the earliest ones calibre returns. Some libraries carry a lot of tags per book. Set to 0 for no limit.").addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.size = 8;
      text.setPlaceholder(String(DEFAULT_SETTINGS.maxTags)).setValue(String(this.plugin.settings.maxTags)).onChange((0, import_obsidian4.debounce)((value) => __async(this, null, function* () {
        const parsed = Number.parseInt(value, 10);
        this.plugin.settings.maxTags = Number.isFinite(parsed) && parsed >= 0 ? parsed : DEFAULT_SETTINGS.maxTags;
        this.plugin.saveData(this.plugin.settings);
      }), DEBOUNCE_TIMEOUT));
    });
    containerEl.createEl("h3", { text: "Note Generation" });
    new import_obsidian4.Setting(containerEl).setName("Note Generation").setDesc("Built-in uses the four templates below to fill in a fixed note structure. Custom Template File reads any Markdown file in your vault and substitutes tokens through the whole thing, frontmatter included \u2014 useful if you already have your own template with fields calibre doesn't provide.").addDropdown((dropdown) => dropdown.addOption("built-in", "Built-in").addOption("custom", "Custom Template File").setValue(this.plugin.settings.noteGeneration).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.noteGeneration = value;
      this.plugin.saveData(this.plugin.settings);
      this.display();
    })));
    if (this.plugin.settings.noteGeneration === "custom") {
      new import_obsidian4.Setting(containerEl).setName("Custom Template File").setDesc("A Markdown file in your vault to use as the note template. See the README for the full list of available tokens, including the _yaml-suffixed and whole-line block variants meant for frontmatter.").addText((text) => {
        text.inputEl.size = 25;
        new TemplateFileSuggest(this.app, text.inputEl);
        text.setPlaceholder("Templates/Book Note.md").setValue(this.plugin.settings.customTemplateFile).onChange((0, import_obsidian4.debounce)((value) => __async(this, null, function* () {
          this.plugin.settings.customTemplateFile = value;
          this.plugin.saveData(this.plugin.settings);
        }), DEBOUNCE_TIMEOUT));
      });
    } else {
      containerEl.createEl("h3", { text: "Note Layout" });
      new import_obsidian4.Setting(containerEl).setName("Heading Template").setDesc("Available: {{title}}, {{author}}, {{authors}}, {{year}}, {{publisher}}, {{series}}, {{id}}.").addTextArea((text) => {
        text.inputEl.rows = 1;
        text.inputEl.cols = 40;
        text.setPlaceholder(DEFAULT_SETTINGS.headingTemplate).setValue(this.plugin.settings.headingTemplate).onChange((0, import_obsidian4.debounce)((value) => __async(this, null, function* () {
          this.plugin.settings.headingTemplate = value;
          this.plugin.saveData(this.plugin.settings);
        }), DEBOUNCE_TIMEOUT));
      });
      new import_obsidian4.Setting(containerEl).setName("Byline Template").setDesc("Available: all heading variables, plus {{byline}} (authors, publisher and year, joined by '\xB7' with any missing pieces dropped). Only used when a byline can be built.").addTextArea((text) => {
        text.inputEl.rows = 1;
        text.inputEl.cols = 40;
        text.setPlaceholder(DEFAULT_SETTINGS.bylineTemplate).setValue(this.plugin.settings.bylineTemplate).onChange((0, import_obsidian4.debounce)((value) => __async(this, null, function* () {
          this.plugin.settings.bylineTemplate = value;
          this.plugin.saveData(this.plugin.settings);
        }), DEBOUNCE_TIMEOUT));
      });
      new import_obsidian4.Setting(containerEl).setName("Cover Template").setDesc("Available: all heading variables, plus {{cover}} (the cover's vault path) and {{coverWidth}}. Only used when a cover was downloaded.").addTextArea((text) => {
        text.inputEl.rows = 1;
        text.inputEl.cols = 40;
        text.setPlaceholder(DEFAULT_SETTINGS.coverTemplate).setValue(this.plugin.settings.coverTemplate).onChange((0, import_obsidian4.debounce)((value) => __async(this, null, function* () {
          this.plugin.settings.coverTemplate = value;
          this.plugin.saveData(this.plugin.settings);
        }), DEBOUNCE_TIMEOUT));
      });
      new import_obsidian4.Setting(containerEl).setName("Description Template").setDesc("Available: all heading variables, plus {{description}} (calibre's comments, converted from HTML to Markdown). Only used when the book has a description.").addTextArea((text) => {
        text.inputEl.rows = 3;
        text.inputEl.cols = 40;
        text.setPlaceholder(DEFAULT_SETTINGS.descriptionTemplate).setValue(this.plugin.settings.descriptionTemplate).onChange((0, import_obsidian4.debounce)((value) => __async(this, null, function* () {
          this.plugin.settings.descriptionTemplate = value;
          this.plugin.saveData(this.plugin.settings);
        }), DEBOUNCE_TIMEOUT));
      });
    }
    new import_obsidian4.Setting(containerEl).setName("Download Cover Image").setDesc("Saves the cover into the import folder alongside the note, so it keeps working if the server address changes.").addToggle((toggle) => toggle.setValue(this.plugin.settings.importCover).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.importCover = value;
      this.plugin.saveData(this.plugin.settings);
    })));
    new import_obsidian4.Setting(containerEl).setName("Cover Folder").setDesc("Where cover images are saved. Leave blank to use the import folder.").addText((text) => {
      text.inputEl.size = 25;
      new FolderSuggest(this.app, text.inputEl);
      text.setPlaceholder("Same as import folder").setValue(this.plugin.settings.coverFolder).onChange((0, import_obsidian4.debounce)((value) => __async(this, null, function* () {
        this.plugin.settings.coverFolder = value;
        this.plugin.saveData(this.plugin.settings);
      }), DEBOUNCE_TIMEOUT));
    });
    new import_obsidian4.Setting(containerEl).setName("Cover Width").setDesc("Display width of the cover image in pixels.").addText((text) => {
      var _a;
      text.inputEl.type = "number";
      text.inputEl.size = 8;
      text.setPlaceholder("350").setValue(String((_a = this.plugin.settings.coverWidth) != null ? _a : 350)).onChange((0, import_obsidian4.debounce)((value) => __async(this, null, function* () {
        const parsed = Number.parseInt(value, 10);
        this.plugin.settings.coverWidth = Number.isFinite(parsed) && parsed > 0 ? parsed : 350;
        this.plugin.saveData(this.plugin.settings);
      }), DEBOUNCE_TIMEOUT));
    });
    new import_obsidian4.Setting(containerEl).setName("Hide Ribbon Icon").addToggle((toggle) => toggle.setValue(this.plugin.settings.hideRibbonIcon).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.hideRibbonIcon = value;
      this.plugin.saveData(this.plugin.settings);
    })));
    new import_obsidian4.Setting(containerEl).setName("Ribbon Icon").setDesc("The icon name to be used.").addText((text) => text.setValue(this.plugin.settings.ribbonIcon).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.ribbonIcon = value;
      this.plugin.saveData(this.plugin.settings);
    })));
  }
};

// src/AdvancedCalibreImporter.ts
var ILLEGAL_FILENAME_CHARS = /[\\/:*?"<>|\u0000-\u001f]/g;
var MAX_FILENAME_LENGTH = 120;
function sanitiseFilename(value) {
  const cleaned = value.replace(ILLEGAL_FILENAME_CHARS, " ").replace(/\s+/g, " ").replace(/^[. ]+|[. ]+$/g, "").trim();
  if (cleaned.length <= MAX_FILENAME_LENGTH) {
    return cleaned;
  }
  return cleaned.slice(0, MAX_FILENAME_LENGTH).trim();
}
function yearOf(date) {
  if (!date) {
    return "";
  }
  const parsed = new Date(date);
  return Number.isNaN(parsed.getTime()) ? "" : String(parsed.getUTCFullYear());
}
function dateOf(date) {
  if (!date) {
    return "";
  }
  const parsed = new Date(date);
  return Number.isNaN(parsed.getTime()) ? "" : parsed.toISOString().slice(0, 10);
}
function renderTemplate(template, values) {
  return template.replace(/\{\{\s*(\w+)\s*\}\}/g, (_match, key) => {
    var _a;
    return (_a = values[key]) != null ? _a : "";
  });
}
function applyFilenameTemplate(template, book) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i;
  const values = {
    title: (_a = book.title) != null ? _a : "Untitled",
    author: (_d = (_c = book.author_sort) != null ? _c : (_b = book.authors) == null ? void 0 : _b.join(", ")) != null ? _d : "Unknown",
    authors: (_g = (_f = (_e = book.authors) == null ? void 0 : _e.join(", ")) != null ? _f : book.author_sort) != null ? _g : "Unknown",
    year: yearOf(book.pubdate),
    publisher: (_h = book.publisher) != null ? _h : "",
    series: (_i = book.series) != null ? _i : "",
    id: String(book.application_id)
  };
  const name = sanitiseFilename(renderTemplate(template, values));
  return name || sanitiseFilename(values.title) || `calibre-${book.application_id}`;
}
function sanitiseTag(tag, style) {
  const trimmed = tag.trim();
  if (style === "none") {
    return trimmed;
  }
  const words = trimmed.split(/\s+/).filter(Boolean);
  let joined;
  if (words.length <= 1) {
    joined = trimmed;
  } else if (style === "camelCase") {
    joined = words.map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join("");
  } else {
    joined = words.join("-");
  }
  return joined.replace(/[^\p{L}\p{N}_\-/]/gu, "").replace(/-{2,}/g, "-").replace(/^-+|-+$/g, "");
}
function processTags(tags, settings) {
  var _a, _b;
  if (!tags || tags.length === 0) {
    return [];
  }
  const style = (_a = settings.tagSpaceHandling) != null ? _a : "hyphenate";
  const cap = (_b = settings.maxTags) != null ? _b : 10;
  const limited = cap > 0 ? tags.slice(0, cap) : tags;
  return limited.map((tag) => sanitiseTag(tag, style));
}
function yamlScalar(value) {
  return /^[\w][\w .,'&()-]*$/.test(value) ? value : JSON.stringify(value);
}
function yamlList(key, values) {
  if (!values || values.length === 0) {
    return "";
  }
  return `${key}: [${values.map(yamlScalar).join(", ")}]
`;
}
function yamlKey(key, value) {
  return value ? `${key}: ${yamlScalar(value)}
` : "";
}
var BLOCK_TOKEN_PATTERN = /^[ \t]*\{\{\s*(tags_yaml|languages_yaml|identifiers_yaml)\s*\}\}[ \t]*\r?\n?/gm;
function buildBlockValues(book, settings) {
  var _a;
  let identifiers = "";
  for (const [scheme, value] of Object.entries((_a = book.identifiers) != null ? _a : {})) {
    if (value) {
      identifiers += `${scheme}: ${JSON.stringify(String(value))}
`;
    }
  }
  return {
    tags_yaml: yamlList("tags", processTags(book.tags, settings)),
    languages_yaml: yamlList("languages", book.languages),
    identifiers_yaml: identifiers
  };
}
function buildCustomValues(book, coverPath, settings) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n;
  const title = (_a = book.title) != null ? _a : "Untitled";
  const displayAuthors = (_d = (_c = (_b = book.authors) == null ? void 0 : _b.join(", ")) != null ? _c : book.author_sort) != null ? _d : "";
  const year = yearOf(book.pubdate);
  const byline = [displayAuthors, book.publisher, year].filter(Boolean).join(" \xB7 ");
  const description = book.comments ? (0, import_obsidian5.htmlToMarkdown)(book.comments).trim() : "";
  const pages = book["pages"];
  const isbn = (_h = (_g = (_e = book.identifiers) == null ? void 0 : _e["isbn"]) != null ? _g : (_f = book.identifiers) == null ? void 0 : _f["ISBN"]) != null ? _h : "";
  return {
    title,
    author: (_i = book.author_sort) != null ? _i : displayAuthors,
    authors: displayAuthors,
    year,
    publisher: (_j = book.publisher) != null ? _j : "",
    series: (_k = book.series) != null ? _k : "",
    seriesIndex: typeof book.series_index === "number" ? String(book.series_index) : "",
    byline,
    cover: coverPath != null ? coverPath : "",
    coverWidth: String((_l = settings.coverWidth) != null ? _l : 350),
    description,
    pages: typeof pages === "number" ? String(pages) : "",
    isbn,
    added: dateOf(book.timestamp),
    calibreUuid: (_m = book.uuid) != null ? _m : "",
    calibreId: String(book.application_id),
    title_yaml: yamlScalar(title),
    author_yaml: yamlScalar((_n = book.author_sort) != null ? _n : displayAuthors),
    authors_yaml: yamlScalar(displayAuthors),
    publisher_yaml: book.publisher ? yamlScalar(book.publisher) : "",
    series_yaml: book.series ? yamlScalar(book.series) : ""
  };
}
function renderCustomTemplate(template, values, blockValues) {
  const withBlocksExpanded = template.replace(BLOCK_TOKEN_PATTERN, (_match, key) => {
    var _a;
    return (_a = blockValues[key]) != null ? _a : "";
  });
  return renderTemplate(withBlocksExpanded, values);
}
var AdvancedCalibreImporter = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  get host() {
    var _a;
    return ((_a = this.settings.address) != null ? _a : "").trim().replace(/\/+$/, "");
  }
  get library() {
    var _a;
    return ((_a = this.settings.importLibrary) != null ? _a : "").trim() || "Calibre_Library";
  }
  fetchLibrary() {
    return __async(this, null, function* () {
      const response = yield (0, import_obsidian5.requestUrl)({
        url: `${this.host}/ajax/books?library_id=${encodeURIComponent(this.library)}`,
        method: "GET",
        throw: false
      });
      if (response.status === 401) {
        throw new Error("The Content server requires a username and password, which metadata import cannot supply yet.");
      }
      if (response.status !== 200) {
        throw new Error(`The Content server returned ${response.status}.`);
      }
      const raw = response.json;
      return Object.values(raw).filter((book) => book !== null);
    });
  }
  buildNote(book, coverPath) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n;
    const title = (_a = book.title) != null ? _a : "Untitled";
    const displayAuthors = (_d = (_c = (_b = book.authors) == null ? void 0 : _b.join(", ")) != null ? _c : book.author_sort) != null ? _d : "";
    const year = yearOf(book.pubdate);
    let frontmatter = "---\n";
    frontmatter += yamlKey("title", title);
    frontmatter += yamlKey("author", (_e = book.author_sort) != null ? _e : displayAuthors);
    frontmatter += yamlKey("publisher", book.publisher);
    frontmatter += yamlKey("published", dateOf(book.pubdate));
    frontmatter += yamlList("tags", processTags(book.tags, this.settings));
    frontmatter += yamlList("languages", book.languages);
    const pages = book["pages"];
    if (typeof pages === "number") {
      frontmatter += `pages: ${pages}
`;
    }
    for (const [scheme, value] of Object.entries((_f = book.identifiers) != null ? _f : {})) {
      if (value) {
        frontmatter += `${scheme}: ${JSON.stringify(String(value))}
`;
      }
    }
    if (book.series) {
      frontmatter += yamlKey("series", book.series);
      if (typeof book.series_index === "number") {
        frontmatter += `series-index: ${book.series_index}
`;
      }
    }
    frontmatter += yamlKey("added", dateOf(book.timestamp));
    frontmatter += yamlKey("calibre-uuid", book.uuid);
    frontmatter += `calibre-id: ${book.application_id}
`;
    frontmatter += "---\n\n";
    const byline = [displayAuthors, book.publisher, year].filter(Boolean).join(" \xB7 ");
    const description = book.comments ? (0, import_obsidian5.htmlToMarkdown)(book.comments).trim() : "";
    const bodyValues = {
      title,
      author: (_g = book.author_sort) != null ? _g : displayAuthors,
      authors: displayAuthors,
      year,
      publisher: (_h = book.publisher) != null ? _h : "",
      series: (_i = book.series) != null ? _i : "",
      id: String(book.application_id),
      byline,
      cover: coverPath != null ? coverPath : "",
      coverWidth: String((_j = this.settings.coverWidth) != null ? _j : 350),
      description
    };
    const sections = [
      renderTemplate((_k = this.settings.headingTemplate) != null ? _k : DEFAULT_SETTINGS.headingTemplate, bodyValues)
    ];
    if (byline) {
      sections.push(renderTemplate((_l = this.settings.bylineTemplate) != null ? _l : DEFAULT_SETTINGS.bylineTemplate, bodyValues));
    }
    if (coverPath) {
      sections.push(renderTemplate((_m = this.settings.coverTemplate) != null ? _m : DEFAULT_SETTINGS.coverTemplate, bodyValues));
    }
    if (description) {
      sections.push(renderTemplate((_n = this.settings.descriptionTemplate) != null ? _n : DEFAULT_SETTINGS.descriptionTemplate, bodyValues));
    }
    const body = sections.join("\n\n") + "\n";
    return frontmatter + body;
  }
  buildCustomNote(book, coverPath) {
    return __async(this, null, function* () {
      var _a;
      const templatePath = ((_a = this.settings.customTemplateFile) != null ? _a : "").trim();
      if (!templatePath) {
        throw new Error("No Custom Template File is set in Advanced Calibre settings.");
      }
      const file = this.app.vault.getAbstractFileByPath((0, import_obsidian5.normalizePath)(templatePath));
      if (!(file instanceof import_obsidian5.TFile)) {
        throw new Error(`Custom Template File not found: ${templatePath}`);
      }
      const template = yield this.app.vault.read(file);
      const values = buildCustomValues(book, coverPath, this.settings);
      const blockValues = buildBlockValues(book, this.settings);
      return renderCustomTemplate(template, values, blockValues);
    });
  }
  saveCover(book, noteFolder) {
    return __async(this, null, function* () {
      var _a, _b, _c;
      const response = yield (0, import_obsidian5.requestUrl)({
        url: `${this.host}/get/cover/${book.application_id}/${encodeURIComponent(this.library)}`,
        method: "GET",
        throw: false
      });
      if (response.status !== 200) {
        throw new Error(`the server returned ${response.status} for the cover`);
      }
      if (!((_a = response.arrayBuffer) == null ? void 0 : _a.byteLength)) {
        throw new Error("the server returned an empty cover");
      }
      const folder = (0, import_obsidian5.normalizePath)(((_b = this.settings.coverFolder) != null ? _b : "").trim() || noteFolder);
      yield this.ensureFolder(folder);
      const name = sanitiseFilename((_c = book.title) != null ? _c : `calibre-${book.application_id}`);
      const path = (0, import_obsidian5.normalizePath)(`${folder}/${name}.jpg`);
      if (!this.app.vault.getAbstractFileByPath(path)) {
        yield this.app.vault.createBinary(path, response.arrayBuffer);
      }
      return path;
    });
  }
  ensureFolder(folder) {
    return __async(this, null, function* () {
      if (!folder || this.app.vault.getAbstractFileByPath(folder)) {
        return;
      }
      yield this.app.vault.createFolder(folder);
    });
  }
  importBook(book) {
    return __async(this, null, function* () {
      var _a, _b;
      const folder = (0, import_obsidian5.normalizePath)(((_a = this.settings.importFolder) != null ? _a : "").trim() || "Sources");
      yield this.ensureFolder(folder);
      const basename = applyFilenameTemplate((_b = this.settings.filenameTemplate) != null ? _b : "{{author}} - {{title}}", book);
      const path = (0, import_obsidian5.normalizePath)(`${folder}/${basename}.md`);
      const existing = this.app.vault.getAbstractFileByPath(path);
      if (existing instanceof import_obsidian5.TFile) {
        new import_obsidian5.Notice(`Already imported: ${basename}`);
        return existing;
      }
      let coverPath = null;
      if (this.settings.importCover) {
        try {
          coverPath = yield this.saveCover(book, folder);
        } catch (e) {
          console.error("calibre: could not save cover", e);
          new import_obsidian5.Notice(`Imported without a cover \u2014 ${e.message}`, 8e3);
        }
      }
      const content = this.settings.noteGeneration === "custom" ? yield this.buildCustomNote(book, coverPath) : this.buildNote(book, coverPath);
      const file = yield this.app.vault.create(path, content);
      new import_obsidian5.Notice(`Imported ${basename}`);
      return file;
    });
  }
};

// src/AdvancedCalibreView.tsx
var import_obsidian6 = __toModule(require("obsidian"));
var ip = __toModule(require_ip());
var ADVANCED_CALIBRE_VIEW_TYPE = "advanced-calibre-view";
function extractHost(value) {
  const trimmed = value.trim();
  if (!trimmed) {
    return "";
  }
  try {
    return new URL(trimmed).hostname;
  } catch (e) {
  }
  try {
    return new URL(`http://${trimmed}`).hostname;
  } catch (e) {
    return trimmed;
  }
}
var AdvancedCalibreView = class extends import_obsidian6.ItemView {
  constructor(leaf, settings) {
    super(leaf);
    this.settings = settings;
    this.closed = false;
  }
  getViewType() {
    return ADVANCED_CALIBRE_VIEW_TYPE;
  }
  getDisplayText() {
    return this.settings.displayText;
  }
  onOpen() {
    return __async(this, null, function* () {
      var _a, _b;
      const container = this.containerEl.children[1];
      try {
        if (!((_a = this.settings.address) == null ? void 0 : _a.trim())) {
          container.createDiv({
            text: "No Calibre server address is set. Add your Content server address in Settings \u2192 Community plugins \u2192 Advanced Calibre.",
            cls: "advanced-calibre-message"
          });
          return;
        }
        const iframe = container.createEl("iframe");
        iframe.setAttribute("sandbox", "allow-forms allow-presentation allow-same-origin allow-scripts allow-modals allow-downloads allow-popups");
        const localIp = extractHost((_b = this.settings.localIpOverride) != null ? _b : "") || ip.address();
        const address2 = this.settings.replaceLocalIp ? this.settings.address.replace("localhost", localIp) : this.settings.address;
        iframe.src = address2;
        this.checkReachable(container, address2);
      } catch (e) {
        console.error(e);
        const error = container.createDiv({ text: e.toString() });
        error.style.color = "var(--text-title-h1)";
      }
    });
  }
  checkReachable(container, address2) {
    return __async(this, null, function* () {
      try {
        yield (0, import_obsidian6.requestUrl)({ url: address2, method: "GET", throw: false });
        return;
      } catch (e) {
      }
      if (this.closed) {
        return;
      }
      const notice = container.createDiv({ cls: "advanced-calibre-message advanced-calibre-overlay" });
      notice.createEl("p", { text: `Couldn't reach the Calibre server at ${address2}` });
      notice.createEl("p", {
        text: "Check that Calibre's Content server is running (Connect/share \u2192 Start Content server) and that the address above is correct."
      });
    });
  }
  onClose() {
    return __async(this, null, function* () {
      this.closed = true;
    });
  }
};

// src/main.tsx
var AdvancedCalibrePlugin = class extends import_obsidian7.Plugin {
  onload() {
    return __async(this, null, function* () {
      try {
        yield this.loadSettings();
        this.addSettingTab(new AdvancedCalibreSettingTab(this.app, this));
        (0, import_obsidian7.addIcon)(ADVANCED_CALIBRE_ICON_ID, ADVANCED_CALIBRE_ICON_SVG);
        this.registerView(ADVANCED_CALIBRE_VIEW_TYPE, (leaf) => new AdvancedCalibreView(leaf, this.settings));
        if (!this.settings.hideRibbonIcon) {
          this.addRibbonIcon(this.settings.ribbonIcon, "Advanced Calibre", () => __async(this, null, function* () {
            this.activateView();
          }));
        }
        this.addCommand({
          id: "open",
          name: "Open",
          callback: () => this.activateView()
        });
        this.addCommand({
          id: "open-horizontally",
          name: "Open horizontally",
          callback: () => this.activateView("horizontal")
        });
        this.addCommand({
          id: "open-vertically",
          name: "Open vertically",
          callback: () => this.activateView("vertical")
        });
        this.addCommand({
          id: "import-metadata",
          name: "Import book metadata",
          callback: () => this.importMetadata()
        });
      } catch (error) {
        console.log(`Load error. ${error}`);
      }
    });
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
      if (this.settings.ribbonIcon === "calibre") {
        this.settings.ribbonIcon = ADVANCED_CALIBRE_ICON_ID;
        yield this.saveData(this.settings);
      }
    });
  }
  activateView(direction) {
    return __async(this, null, function* () {
      const mode = direction != null ? direction : this.settings.splitDirection;
      const leaf = mode === "tab" ? this.app.workspace.getLeaf("tab") : this.app.workspace.getLeaf("split", mode);
      yield leaf.setViewState({
        type: ADVANCED_CALIBRE_VIEW_TYPE,
        active: true
      });
      this.app.workspace.revealLeaf(leaf);
    });
  }
  importMetadata() {
    return __async(this, null, function* () {
      const importer = new AdvancedCalibreImporter(this.app, this.settings);
      const notice = new import_obsidian7.Notice("Loading your calibre library...", 0);
      try {
        const books = yield importer.fetchLibrary();
        notice.hide();
        if (books.length === 0) {
          new import_obsidian7.Notice("No books found in that calibre library.");
          return;
        }
        new BookSuggestModal(this.app, books, (book) => __async(this, null, function* () {
          try {
            const file = yield importer.importBook(book);
            if (file && this.settings.autoOpenAfterImport) {
              yield this.app.workspace.getLeaf(false).openFile(file);
            }
          } catch (e) {
            console.error(e);
            new import_obsidian7.Notice(`Could not import that book: ${e.message}`);
          }
        })).open();
      } catch (e) {
        notice.hide();
        console.error(e);
        new import_obsidian7.Notice(`Could not reach calibre: ${e.message}`, 8e3);
      }
    });
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(ADVANCED_CALIBRE_VIEW_TYPE);
  }
};
